name: Bug Report Form
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Can you please describe the bug?
    validations:
      required: true
  - type: textarea
    id: type-definitions
    attributes:
      label: Type Definitions
      description: Can you please provide your type definitions when you encountered this bug?
      render: graphql
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Can you please provide the steps required to reproduce this bug? Please use code blocks - a template is already provided.
      value:  |
        1. Add some test data with the following Mutation:
        
        ```graphql
        mutation {
          someMutation {
            ...someFields
          }
        }
        ```
        
        2. Query the data using the following Query:
        
        ```graphql
        query {
          someQuery {
            ...someFields
          }
        }
        ```
        
        3. See the error.
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What product were you using when you encountered this bug?
      options:
        - Neo4j GraphQL Library
        - OGM
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the product were you using when you encountered this bug?
    validations:
      required: true
